[database]
server = "sampleport"
port = 5432
database = "xm"
user = "user"
password = "password"
automigrate = false
timeout = 10
log = false

[server.grpc]
address = "sampleport"
port = "8091"
timeout = 10
prod = false

[secrets]
ttl = 20
jwt = "samplejwtkey"
